version: '3.8'
services:
  db1:
    image: postgres:15
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"

  db2:
    image: postgres:15
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5434:5432"