openapi: 3.0.1
info:
  title: User Aggregator API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users from all configured data sources
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        surname:
          type: string